# Scan entire message thread / session / checklist for unimplemented requests
# Outputs unimplemented tasks to unimplemented-requests.md for /push to execute

$OutputFile = "unimplemented-requests.md"
$Root = Resolve-Path "."

$header = "# Unimplemented Requests — Scanned from Thread / Session / Checklist`nGenerated by /push scanner`n`n"
$header | Out-File -FilePath $OutputFile -Encoding utf8

function Add-Item($Category, $Description, $Source) {
    Add-Content -Path $OutputFile -Value "- [$Category] $Description (from $Source)" -Encoding utf8
}

# 1. Read TASKS_CHECKLIST.md for uncompleted items
$Checklist = Join-Path $Root "TASKS_CHECKLIST.md"
if (Test-Path $Checklist) {
    $lines = Get-Content -Path $Checklist
    $inTasks = $false
    foreach ($line in $lines) {
        if ($line -match "## " ) { $inTasks = $false }
        if ($line -match "- \[ \]" ) {
            $desc = $line -replace "- \[ \] ", ""
            Add-Item "CheckList" $desc $Checklist
        }
    }
}

# 2. Scan session / message storage
$sources = @(
    (Join-Path $Root ".claude"),
    (Join-Path $Root ".opencode"),
    (Join-Path $Root "packages/opencode/src/session"),
    (Join-Path $Root ".agents")
)
foreach ($dir in $sources) {
    if (Test-Path $dir) {
        $files = Get-ChildItem -Recurse -File -Path $dir -ErrorAction SilentlyContinue | Where-Object { $_.Extension -in @('.md','.txt','.json','.ts') } | Select-Object -First 10
        foreach ($f in $files) {
            $content = Get-Content -Path $f.FullName -Raw -ErrorAction SilentlyContinue | Select-String -Pattern "request|implement|build|screenshot|release|pipeline|add" | Select-Object -First 3
            if ($content) {
                foreach ($match in $content) {
                    $lineText = $match.Line.Trim()
                    $lineText = $lineText -replace '`n', ' '
                    Add-Item "Session/Chat" $lineText $f.FullName
                }
            }
        }
    }
}

# 3. Scan previous user messages from this session (current chat context captured in environment / file references)
# Since persistent thread log isn't available, we capture the current instruction set as reference tasks.
Add-Item "Thread/Instruction" "Complete all tasks in TASKS_CHECKLIST.md (swarm, parked, skipped, previous incomplete)" "current-session"
Add-Item "Thread/Instruction" "Add screenshots for all versions: web, .exe, .apk, .dmg, .ipa, .deb, .snap" "current-session"
Add-Item "Thread/Instruction" "Update all documentation (README, CHANGELOG, RELEASE reports, docs)" "current-session"
Add-Item "Thread/Instruction" "Create new updated release with updated assets" "current-session"
Add-Item "Thread/Instruction" "Create build pipelines for all assets (.dmg, .ipa, .deb, .snap) if missing" "current-session"
Add-Item "Thread/Instruction" "Execute build pipelines when /push is run" "current-session"

Write-Host "[SCANNER] Unimplemented requests written to $OutputFile" -ForegroundColor Green
$count = (Get-Content $OutputFile | Measure-Object).Count
Write-Host "[SCANNER] Count: $count"
